name: Deploy to VPS

on:
  push:
    branches:
      - main # Chạy workflow mỗi khi push code lên branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT || 22 }}
          script: |
            cd ${{ secrets.VM_TARGET_DIR || '/root/bot_dis' }}
            git pull origin main
            if [ -d "venv" ]; then
              source venv/bin/activate
              pip install -r requirements.txt
            else
              pip install -r requirements.txt
            fi
            npm install
            pm2 restart bot_dis || pm2 start "./venv/bin/python main.py" --name "bot_dis"
            pm2 save

